from scrapers.event_detail_scraper import scrap_event_detail
from scrapers.events_scraper import scrap_all_events
from scrapers.fighters_scraper import scrap_fighters
from scrapers.match_detail_scraper import scrap_match_detail_sig, scrap_match_detail_total